logging:
  level:
    ROOT: DEBUG

server:
  port: 8000
  servlet:
    context-path: /mogi
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/mogi
    username: postgres
    password: root
  jpa:
    generate-ddl: true
    
    logging:
  level:
    ROOT: DEBUG
    