server:
  port: 8000
  servlet:
    context-path: /mogi
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mogi
    username: postgres
    password: 123Fatec
  jpa:
    generate-ddl: true